language: node_js
node_js:
  - 6
env:
  - MOCHA_REPORTER=console
cache:
  directories:
    - node_modules
before_install:
  # Install meteor and spacejam
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH
  - meteor npm install --save bcrypt
  - npm install -g spacejam
script:
  - spacejam test --driver-package practicalmeteor:mocha
services:
  - mongodb
