language: node_js
node_js:
  - "7"
env:
  - MOCHA_REPORTER=console
before_install:
  # Install meteor and spacejam
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH
  - meteor npm install
  - npm install -g spacejam
script:
  - spacejam test --driver-package practicalmeteor:mocha
services:
  - mongodb
